# https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/
# Install Jekyll and other dependencies from the GitHub Pages gem: `$ bundle install`
source 'https://rubygems.org'
gem 'jekyll'
gem 'kramdown'
gem 'github-pages', group: :jekyll_plugins
gem 'webrick'

gem "csv", "~> 3.3"
gem "base64", "~> 0.2.0"
gem "bigdecimal", "~> 3.2"
